version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - C:/Users/aumee/Documents/Olist_Analysis/cleaned_data:/cleaned_data